version: '3'
services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - '5672:5672'

  kafka:
    image: bashj79/kafka-kraft
    ports:
      - '9092:9092'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
